export default [
  {
    name: 'system',
    path: '/system',
    component: '@/layouts/index',
    routes: [
      {
        title: '首页',
        name: 'home',
        hidden: false,
        path: '/system/home',
        component: '@/pages/login/home',
      },
      {
        title: '用户管理',
        name: 'user',
        hidden: false,
        path: '/system/user',
        component: '@/pages/system/user/user',
      },
      {
        title: '角色管理',
        name: 'role',
        hidden: false,
        path: '/system/role',
        component: '@/pages/system/role/role',
      },
      {
        title: '菜单管理',
        name: 'menu',
        hidden: false,
        path: '/system/menu',
        component: '@/pages/system/menu/menu',
      },
      {
        title: '组织架构',
        name: 'structure',
        hidden: false,
        path: '/system/structure',
        component: '@/pages/system/structure/structure',
      },
      {
        title: '字典项',
        name: 'dict',
        hidden: false,
        path: '/system/dict',
        component: '@/pages/system/dict/dict',
      },
      {
        title: '字典项详情',
        name: 'dict',
        hidden: true,
        path: '/system/dict_info',
        component: '@/pages/system/dict/dict_info',
      },
      {
        title: '流程设定',
        name: 'process_set',
        hidden: false,
        path: '/system/process_set',
        component: '@/pages/system/process_set/process_set',
      },
      {
        title: '日志审计',
        name: 'audit',
        hidden: false,
        path: '/system/audit',
        component: '@/pages/system/dict/dict',
      },
      {
        title: '流程与任务',
        name: 'task',
        hidden: false,
        path: '/system/task',
        component: '@/pages/process/task/task',
      },
      {
        title: '历史流程',
        name: 'task_history',
        hidden: false,
        path: '/system/task_history',
        component: '@/pages/process/task_history/task_history',
      },
      {
        title: '集团固定资产',
        name: 'group_asstes',
        hidden: false,
        path: '/system/group_asstes',
        component: '@/pages/assets/group/group',
      },
      {
        title: '部门资产列表',
        name: 'department_assets',
        hidden: false,
        path: '/system/department_assets',
        component: '@/pages/assets/department/department',
      },
      {
        title: '个人资产列表',
        name: 'personal_assets',
        hidden: false,
        path: '/system/personal_assets',
        component: '@/pages/assets/personal/personal',
      },
      {
        title: '资产领用',
        name: 'assets_recipients',
        hidden: false,
        path: '/system/assets_recipients',
        component: '@/pages/assets/recipients/recipients',
      },
      {
        title: '资产租借',
        name: 'assets_loan',
        hidden: false,
        path: '/system/assets_loan',
        component: '@/pages/assets/loan/loan',
      },
    ],
  },
  {
    path: '/login',
    name: 'Login',
    title: '登录',
    hidden: true,
    component: '@/pages/login/login',
  },
];
